require(knitr)
require(markdown)
# setwd("~/GitHub/Project-for-Getting-and-Cleaning-Data/")
setwd("~/GitHub/Project-for-Getting-and-Cleaning-Data/")
knit("run_analysis.Rmd", encoding="ISO8859-1")
markdownToHTML("run_analysis.md", "run_analysis.html")
